$raw = [System.IO.File]::ReadAllBytes("index.html")
$text = [System.Text.Encoding]::UTF8.GetString($raw)

# Fix double-encoded UTF-8 (Mojibake) — Ã© = e with accent, etc.
$text = $text.Replace("Ã¡", "á")
$text = $text.Replace("Ã©", "é")
$text = $text.Replace("Ã­", "í")
$text = $text.Replace("Ã³", "ó")
$text = $text.Replace("Ãº", "ú")
$text = $text.Replace("Ã±", "ñ")
$text = $text.Replace("ÃÁ", "Á")
$text = $text.Replace("Ã‰", "É")
$text = $text.Replace("Ã", "Í")
$text = $text.Replace("Ã"", "Ó")
$text = $text.Replace("Ãš", "Ú")
$text = $text.Replace("Ã'", "Ñ")
$text = $text.Replace("Â¿", "¿")
$text = $text.Replace("Â¡", "¡")
$text = $text.Replace("Â°", "°")
$text = $text.Replace("Â·", "·")
$text = $text.Replace("Ã¼", "ü")
$text = $text.Replace("Ã‡", "Ç")
$text = $text.Replace("Ã©", "é")
$text = $text.Replace("Ã ", "à")
$text = $text.Replace("Ã¨", "è")
$text = $text.Replace("Ã®", "î")
$text = $text.Replace("Ã´", "ô")
$text = $text.Replace("Ã»", "û")
$text = $text.Replace("Ã„", "Ä")
$text = $text.Replace("Ã–", "Ö")
$text = $text.Replace("Ãœ", "Ü")
$text = $text.Replace("Ã¤", "ä")
$text = $text.Replace("Ã¶", "ö")

$outBytes = [System.Text.Encoding]::UTF8.GetBytes($text)
[System.IO.File]::WriteAllBytes("index.html", $outBytes)
Write-Output "Done. File size: $($outBytes.Length) bytes"
